### ISSUE TITLE
SVG Logo doesn't display

### ISSUE THREAD

**Issue by saadq** [jaredpalmer/react-parcel-example#6]
For some reason, the SVG doesn't seem to be displaying properly:

![screen shot 2017-12-09 at 1 23 48 am](https://user-images.githubusercontent.com/5678694/33793141-ab2ca510-dc7f-11e7-8855-07d5313b883f.png)

---

Steps to reproduce:

1. Clone this repo and `cd` into its root project directory
2. Run `npm install` or `yarn` to install dependencies
3. Run `npm start` and head over to localhost:1234

**Comment by cktang88** [comment]
Yes this is an issue for me as well.

**Comment by drejohnson** [comment]
I have this issue also

**Comment by ryh** [comment]
I had this issue as well, both on chrome and safari 
response header for the .svg
```
Accept-Ranges:bytes
Cache-Control:public, max-age=0
Connection:keep-alive
Content-Length:415
Content-Type:text/html; charset=UTF-8
Date:Sun, 17 Dec 2017 06:51:09 GMT
ETag:W/"19f-160633ba65a"
Last-Modified:Sun, 17 Dec 2017 06:49:01 GMT
```
why the `content-Type:text/html` wrong?

**Comment by cktang88** [comment]
If you go to [](http://localhost:1234/323603fa204d5e60cb57d3b0c5f5c694.svg), it actually redirects to index.html, which is why the content-Type is text/html @ryh . If you prepend the svg with [dist/](url), it works for me. This was supposed to be fixed by parcel-bundler/parcel#160, but it still seems to be an issue? I've updated to the latest v1.2.0

**Comment by ryh** [comment]
For the record: I did not see 301, 302 for that response.
@cktang88 I am using parcel v1.2.0 too.

**Comment by ee0pdt** [comment]
I see the same issue with SVG's with v1.2.0 when serving the build using http-server

```
[Mon Dec 18 2017 08:22:18 GMT+0000 (GMT)] "GET /205b490b53dc64ea484929981c6ba32a.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
[Mon Dec 18 2017 08:22:18 GMT+0000 (GMT)] "GET /205b490b53dc64ea484929981c6ba32a.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
[Mon Dec 18 2017 08:22:18 GMT+0000 (GMT)] "GET /dist//29841e27f4ed6aa597b2fd66b8992081.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
[Mon Dec 18 2017 08:22:18 GMT+0000 (GMT)] "GET /dist//29841e27f4ed6aa597b2fd66b8992081.svg" Error (404): "Not found"
```

**Comment by ee0pdt** [comment]
To clarify, `yarn start` works correctly, it's `npm run build` that fails to load SVG

**Comment by ee0pdt** [comment]
OK, no I'm wrong, it's only the typescript branch that works, master is broken in both cases:

master dev: broken
master build: broken
typescript dev: working
typescript build: broken

**Comment by nick-ChenZe** [comment]
#10

**Comment by nick-ChenZe** [comment]
This can also solve the problem, but i don't recommend it 😁
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import fs from 'fs';
const logo = fs.readFileSync(__dirname + '/logo.svg');

const App = () => (
  <div className="App">
    <div className="App-Logo" dangerouslySetInnerHTML={{__html: logo}} />
    <h1 className="App-Title">Hello Parcel x React</h1>
  </div>
);

ReactDOM.render(<App />, document.getElementById('root'));

// Hot Module Replacement
if (module.hot) {
  module.hot.accept();
}
```

```css
.App-Logo {
  transition: 3s;
  height: 100px;
  width: 100px;
}

.App:hover > .App-Logo {
  transform: rotate(1080deg);
}
```

**Comment by ee0pdt** [comment]
@nick-ChenZe - thanks! I think I'll wait for Parcel to fix this!

**Comment by JeffersonFilho** [comment]
I just followed the steps and everything is working just fine for me.

**Comment by ee0pdt** [comment]
@JeffersonFilho I've just pulled the latest version and tested with the latest version of Parcel.

Good News: master now works correctly
Bad News: Typescript branch still broken when you build it - but the ts branch has not been updated recently. If have time I'll try to poke and see what the differences are

**Comment by cktang88** [comment]
@saadq seems like this issue should now be closed.

**Comment by ee0pdt** [comment]
@saadq @cktang88 The typescript branch is still not fixed, I would not close this issue until that is resolved or at least documented.

**Comment by jaredpalmer** [comment]
This is fixed.
